const trainees = [
  { name: "아담 나가이", img: "images/1.jpg" },
  { name: "나카마루 아쥬", img: "images/2.jpg" },
  { name: "엄 쑹카바띤", img: "images/3.jpg" },
  { name: "아처 위", img: "images/4.jpg" },
  { name: "시노가야 아유무", img: "images/5.jpg" },
  { name: "코바야시 치사토", img: "images/6.jpg" },
  { name: "카토 다이키", img: "images/7.jpg" },
  { name: "곽동민", img: "images/8.jpg" },
  { name: "스에카와 에이타", img: "images/9.jpg" },
  { name: "카네다 에이토", img: "images/10.jpg" },
  { name: "사쿠라이 후마", img: "images/11.jpg" },
  { name: "오기사와라 주제페 케이", img: "images/12.jpg" },
  { name: "오가사와라 주제페 케이", img: "images/13.jpg" },
  { name: "쿠라하시 고텐", img: "images/14.jpg" },
  { name: "호리오 히지리", img: "images/15.jpg" },
  { name: "주케란 히로토", img: "images/16.jpg" },
  { name: "유현승", img: "images/17.jpg" },
  { name: "오카다 휴고", img: "images/18.jpg" },
  { name: "야나기야 잇사", img: "images/19.jpg" },
  { name: "윤재용", img: "images/20.jpg" },
  { name: "주앙 제이", img: "images/21.jpg" },
  { name: "마루오 진이치로", img: "images/22.jpg" },
  { name: "카와베 죠", img: "images/23.jpg" },
  { name: "신정욱", img: "images/24.jpg" },
  { name: "카네야스 준세이", img: "images/25.jpg" },
  { name: "우노 카이무", img: "images/26.jpg" },
  { name: "타비 카나데", img: "images/27.jpg" },
  { name: "요코야마 카나메", img: "images/28.jpg" },
  { name: "세키 케이지로", img: "images/29.jpg" },
  { name: "타카마츠 케이스케", img: "images/30.jpg" },
  { name: "오노 케이토", img: "images/31.jpg" },
  { name: "니시야마 켄토", img: "images/32.jpg" },
  { name: "카와이 코세이", img: "images/33.jpg" },
  { name: "테루이 코스케", img: "images/34.jpg" },
  { name: "아사카 코타로", img: "images/35.jpg" },
  { name: "타카야 쿄헤이", img: "images/36.jpg" },
  { name: "다나카 마키", img: "images/37.jpg" },
  { name: "야마네 무사시", img: "images/38.jpg" },
  { name: "츠치다 오스케", img: "images/39.jpg" },
  { name: "호리노 렌", img: "images/40.jpg" },
  { name: "코시미즈 렌", img: "images/41.jpg" },
  { name: "천리키", img: "images/42.jpg" },
  { name: "카미모토 리쿠", img: "images/43.jpg" },
  { name: "하토바 리쿠토", img: "images/44.jpg" },
  { name: "이마에 리쿠토", img: "images/45.jpg" },
  { name: "카이 리쿠야", img: "images/46.jpg" },
  { name: "오세 린토", img: "images/47.jpg" },
  { name: "우에노 루이", img: "images/48.jpg" },
  { name: "이이즈카 료가", img: "images/49.jpg" },
  { name: "이시다 료타", img: "images/50.jpg" },
  { name: "오카도 류가", img: "images/51.jpg" },
  { name: "스기야마 류지", img: "images/52.jpg" },
  { name: "카츠키 세이타", img: "images/53.jpg" },
  { name: "사와이 세나", img: "images/54.jpg" },
  { name: "오신행", img: "images/55.jpg" },
  { name: "이와키 신지", img: "images/56.jpg" },
  { name: "미야자키 신스케", img: "images/57.jpg" },
  { name: "니시자키 슈", img: "images/58.jpg" },
  { name: "야마시타 슈", img: "images/59.jpg" },
  { name: "박시영", img: "images/60.jpg" },
  { name: "사토 소라", img: "images/61.jpg" },
  { name: "토노 소타", img: "images/62.jpg" },
  { name: "후지마키 타이가", img: "images/63.jpg" },
  { name: "마츠다 타이가", img: "images/64.jpg" },
  { name: "카나쿠라 타쿠미", img: "images/65.jpg" },
  { name: "쿠마베 타쿠토", img: "images/66.jpg" },
  { name: "미야자토 타쿠토", img: "images/67.jpg" },
  { name: "미나미히라 타츠야", img: "images/68.jpg" },
  { name: "모리이 테루", img: "images/69.jpg" },
  { name: "키타바야시 테토라", img: "images/70.jpg" },
  { name: "후지요시 토키야", img: "images/71.jpg" },
  { name: "마스다 토모키", img: "images/72.jpg" },
  { name: "하마다 토와", img: "images/73.jpg" },
  { name: "아기날도 트리스탄 제임스", img: "images/74.jpg" },
  { name: "리 웨이저", img: "images/75.jpg" },
  { name: "요한 엠마누엘", img: "images/76.jpg" },
  { name: "야다 요시키", img: "images/77.jpg" },
  { name: "고토 유키", img: "images/78.jpg" },
  { name: "오카다 유마", img: "images/79.jpg" },
  { name: "아베 유라", img: "images/80.jpg" },
  { name: "오바야시 유세이", img: "images/81.jpg" },
  { name: "사노 유세이", img: "images/82.jpg" },
  { name: "혼죠 아키라", img: "images/83.jpg" },
  { name: "코지마 아유무", img: "images/84.jpg" },
  { name: "이치카와 다이키", img: "images/85.jpg" },
  { name: "카와무라 하쿠토", img: "images/86.jpg" },
  { name: "무라마츠 하루쿠", img: "images/87.jpg" },
  { name: "타카기 하루토", img: "images/88.jpg" },
  { name: "히라시마 히카루", img: "images/89.jpg" },
  { name: "사가와 히로카즈", img: "images/90.jpg" },
  { name: "이현재", img: "images/91.jpg" },
  { name: "아베 이츠키", img: "images/92.jpg" },
  { name: "이중훈", img: "images/93.jpg" },
  { name: "리우 카이치", img: "images/94.jpg" },
  { name: "쿠로사키 칸타", img: "images/95.jpg" },
  { name: "코 케이신", img: "images/96.jpg" },
  { name: "켄모츠 키나리", img: "images/97.jpg" },
  { name: "오자와 코신", img: "images/98.jpg" },
  { name: "아오누마 코시로", img: "images/99.jpg" },
  { name: "코바야시 코", img: "images/100.jpg" },
  { name: "모리 메이", img: "images/101.jpg" },
  { name: "마이클 민 맥카프리", img: "images/102.jpg" },
  { name: "패트릭 판 레", img: "images/103.jpg" },
  { name: "카사하라 렌", img: "images/104.jpg" },
  { name: "에구치 렌토", img: "images/105.jpg" },
  { name: "코바야시 렌토", img: "images/106.jpg" },
  { name: "오치아이 리오", img: "images/107.jpg" },
  { name: "미즈가미 루이", img: "images/108.jpg" },
  { name: "코야우치 루카", img: "images/109.jpg" },
  { name: "사이토 세이", img: "images/110.jpg" },
  { name: "후지모토 신세이", img: "images/111.jpg" },
  { name: "이이다 슈마", img: "images/112.jpg" },
  { name: "마츠다 소고", img: "images/113.jpg" },
  { name: "타카하시 소라", img: "images/114.jpg" },
  { name: "니시다 소시", img: "images/115.jpg" },
  { name: "오카모토 타쿠토", img: "images/116.jpg" },
  { name: "오사와 유고", img: "images/117.jpg" },
  { name: "후지이 유세이", img: "images/118.jpg" },
  { name: "오카모토 유토", img: "images/119.jpg" }
];
